// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	CommentID   int64     `json:"comment_id"`
	PostID      int64     `json:"post_id"`
	UserID      int64     `json:"user_id"`
	CommentText string    `json:"comment_text"`
	CreatedAt   time.Time `json:"created_at"`
}

type Currency struct {
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type FollowRoom struct {
	FollowRoomID int64     `json:"follow_room_id"`
	UserID       int64     `json:"user_id"`
	RoomID       int64     `json:"room_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type MainCategory struct {
	CategoryName string    `json:"category_name"`
	CreatedAt    time.Time `json:"created_at"`
}

type Meal struct {
	MealID    int64     `json:"meal_id"`
	PostID    int64     `json:"post_id"`
	UserID    int64     `json:"user_id"`
	Calorie   int64     `json:"calorie"`
	CreatedAt time.Time `json:"created_at"`
}

type Post struct {
	PostID       int64          `json:"post_id"`
	UserID       int64          `json:"user_id"`
	MainCategory string         `json:"main_category"`
	RoomID       sql.NullInt64  `json:"room_id"`
	PostText     sql.NullString `json:"post_text"`
	PhotoUrl     sql.NullString `json:"photo_url"`
	Location     interface{}    `json:"location"`
	MealFlag     bool           `json:"meal_flag"`
	// 1:公開、2:ルーム内で公開、3:非公開
	PublicTypeNo string    `json:"public_type_no"`
	CreatedAt    time.Time `json:"created_at"`
}

type PostSubcategory struct {
	PostSubcategoryID int64  `json:"post_subcategory_id"`
	PostID            int64  `json:"post_id"`
	CategoryName      string `json:"category_name"`
}

type Room struct {
	RoomID          int64          `json:"room_id"`
	OwnerID         sql.NullInt64  `json:"owner_id"`
	RoomName        sql.NullString `json:"room_name"`
	RoomDescription sql.NullString `json:"room_description"`
	// TRUE:自由に出入り可能、FALSE:ownerの許可が必要
	FreeEntryFlag bool      `json:"free_entry_flag"`
	CreatedAt     time.Time `json:"created_at"`
}

type SubCategory struct {
	CategoryName string    `json:"category_name"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	UserID    int64     `json:"user_id"`
	Uid       string    `json:"uid"`
	Username  string    `json:"username"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}
