// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Favorite struct {
	FavoriteID int64     `json:"favorite_id"`
	PostID     int64     `json:"post_id"`
	UserID     int64     `json:"user_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type FollowUser struct {
	FollowID     int64     `json:"follow_id"`
	UserID       int64     `json:"user_id"`
	FollowUserID int64     `json:"follow_user_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type MainCategory struct {
	CategoryName string    `json:"category_name"`
	CreatedAt    time.Time `json:"created_at"`
}

type Meal struct {
	MealID    int64     `json:"meal_id"`
	PostID    int64     `json:"post_id"`
	UserID    int64     `json:"user_id"`
	Calorie   int64     `json:"calorie"`
	CreatedAt time.Time `json:"created_at"`
}

type Post struct {
	PostID       int64       `json:"post_id"`
	UserID       int64       `json:"user_id"`
	MainCategory string      `json:"main_category"`
	PostText     *string     `json:"post_text"`
	PhotoUrl     *string     `json:"photo_url"`
	Location     interface{} `json:"location"`
	MealFlag     bool        `json:"meal_flag"`
	// 1:公開、2:フォロワーにのみ公開、3:非公開
	PublicTypeNo string    `json:"public_type_no"`
	CreatedAt    time.Time `json:"created_at"`
}

type PostSubcategory struct {
	PostSubcategoryID int64  `json:"post_subcategory_id"`
	PostID            int64  `json:"post_id"`
	SubcategoryNo     string `json:"subcategory_no"`
	SubCategory       string `json:"sub_category"`
}

type SubCategory struct {
	CategoryName string    `json:"category_name"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	UserID          int64     `json:"user_id"`
	Uid             string    `json:"uid"`
	Username        string    `json:"username"`
	SelfIntro       *string   `json:"self_intro"`
	ProfileImageUrl *string   `json:"profile_image_url"`
	BannerImageUrl  *string   `json:"banner_image_url"`
	CountryCode     *string   `json:"country_code"`
	CreatedAt       time.Time `json:"created_at"`
}
