// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: post_subcategories.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPostSubCategory = `-- name: CreatePostSubCategory :one
INSERT INTO post_subcategories (
  post_id,
  category_no,
  category_id
) VALUES (
  $1, $2, $3
) RETURNING post_id, category_no, category_id
`

type CreatePostSubCategoryParams struct {
	PostID     uuid.UUID `json:"post_id"`
	CategoryNo string    `json:"category_no"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) CreatePostSubCategory(ctx context.Context, arg CreatePostSubCategoryParams) (PostSubcategory, error) {
	row := q.db.QueryRow(ctx, createPostSubCategory, arg.PostID, arg.CategoryNo, arg.CategoryID)
	var i PostSubcategory
	err := row.Scan(&i.PostID, &i.CategoryNo, &i.CategoryID)
	return i, err
}
