// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: post_subcategories.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPostSubCategory = `-- name: CreatePostSubCategory :one
INSERT INTO post_subcategories (
  post_id,
  category_no,
  category_id
) VALUES (
  $1, $2, $3
) RETURNING post_id, category_no, category_id
`

type CreatePostSubCategoryParams struct {
	PostID     uuid.UUID `json:"post_id"`
	CategoryNo string    `json:"category_no"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) CreatePostSubCategory(ctx context.Context, arg CreatePostSubCategoryParams) (PostSubcategory, error) {
	row := q.db.QueryRow(ctx, createPostSubCategory, arg.PostID, arg.CategoryNo, arg.CategoryID)
	var i PostSubcategory
	err := row.Scan(&i.PostID, &i.CategoryNo, &i.CategoryID)
	return i, err
}

const deletePostSubCategory = `-- name: DeletePostSubCategory :exec
DELETE FROM post_subcategories
WHERE post_id = $1 AND category_no = $2
`

type DeletePostSubCategoryParams struct {
	PostID     uuid.UUID `json:"post_id"`
	CategoryNo string    `json:"category_no"`
}

func (q *Queries) DeletePostSubCategory(ctx context.Context, arg DeletePostSubCategoryParams) error {
	_, err := q.db.Exec(ctx, deletePostSubCategory, arg.PostID, arg.CategoryNo)
	return err
}
