// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFavorite(ctx context.Context, arg CreateFavoriteParams) (Favorite, error)
	CreateFollow(ctx context.Context, arg CreateFollowParams) (Follow, error)
	CreateFollowRequest(ctx context.Context, arg CreateFollowRequestParams) (FollowRequest, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePostSubCategory(ctx context.Context, arg CreatePostSubCategoryParams) (PostSubcategory, error)
	CreateSubCategory(ctx context.Context, arg CreateSubCategoryParams) (SubCategory, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFavorite(ctx context.Context, arg DeleteFavoriteParams) (Favorite, error)
	DeleteFollow(ctx context.Context, arg DeleteFollowParams) (Follow, error)
	DeleteFollowRequest(ctx context.Context, arg DeleteFollowRequestParams) (FollowRequest, error)
	DeletePost(ctx context.Context, postID uuid.UUID) error
	DeletePostSubCategory(ctx context.Context, arg DeletePostSubCategoryParams) error
	DeleteSubCategory(ctx context.Context, categoryID uuid.UUID) error
	GetDailyActivitySummaryByMonth(ctx context.Context, arg GetDailyActivitySummaryByMonthParams) ([]GetDailyActivitySummaryByMonthRow, error)
	GetExpenseSummaryByMonth(ctx context.Context, arg GetExpenseSummaryByMonthParams) ([]GetExpenseSummaryByMonthRow, error)
	GetFavorite(ctx context.Context, arg GetFavoriteParams) (Favorite, error)
	GetFollow(ctx context.Context, arg GetFollowParams) (Follow, error)
	GetFollowInfo(ctx context.Context, arg GetFollowInfoParams) (GetFollowInfoRow, error)
	GetFollowRequest(ctx context.Context, arg GetFollowRequestParams) (FollowRequest, error)
	GetFollowRequests(ctx context.Context, followingUid string) ([]GetFollowRequestsRow, error)
	GetFollowUsers(ctx context.Context, uid string) ([]GetFollowUsersRow, error)
	GetOwnPosts(ctx context.Context, uid string) ([]GetOwnPostsRow, error)
	GetPostById(ctx context.Context, postID uuid.UUID) (GetPostByIdRow, error)
	GetPostsByMainCategory(ctx context.Context, arg GetPostsByMainCategoryParams) ([]GetPostsByMainCategoryRow, error)
	GetPostsByMainCategoryAndSubCategory(ctx context.Context, arg GetPostsByMainCategoryAndSubCategoryParams) ([]GetPostsByMainCategoryAndSubCategoryRow, error)
	GetPostsBySubCategory(ctx context.Context, arg GetPostsBySubCategoryParams) ([]GetPostsBySubCategoryRow, error)
	GetPostsByUid(ctx context.Context, arg GetPostsByUidParams) ([]GetPostsByUidRow, error)
	GetPostsCount(ctx context.Context, uid string) (int64, error)
	GetSubCategoryByName(ctx context.Context, categoryName string) (SubCategory, error)
	GetSubCategorySummaryByMonth(ctx context.Context, arg GetSubCategorySummaryByMonthParams) ([]GetSubCategorySummaryByMonthRow, error)
	GetTimelinePosts(ctx context.Context, uid string) ([]GetTimelinePostsRow, error)
	GetUser(ctx context.Context, uid string) (User, error)
	UpdateFollowRequestToAccepted(ctx context.Context, requestID uuid.UUID) (FollowRequest, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateRequestToRejected(ctx context.Context, requestID uuid.UUID) (FollowRequest, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
