// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateMainCategory(ctx context.Context, categoryName string) (MainCategory, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePostSubCategory(ctx context.Context, arg CreatePostSubCategoryParams) (PostSubcategory, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetFollowUsers(ctx context.Context, uid string) ([]GetFollowUsersRow, error)
	GetMainCategories(ctx context.Context) ([]MainCategory, error)
	GetMainCategory(ctx context.Context, categoryName string) (MainCategory, error)
	GetPostById(ctx context.Context, postID uuid.UUID) (GetPostByIdRow, error)
	GetPostSubCategoryByPostId(ctx context.Context, postID uuid.UUID) ([]PostSubcategory, error)
	GetPostsByCategory(ctx context.Context, arg GetPostsByCategoryParams) ([]GetPostsByCategoryRow, error)
	GetPostsByFollowing(ctx context.Context, uid string) ([]GetPostsByFollowingRow, error)
	GetPostsBySubCategory(ctx context.Context, arg GetPostsBySubCategoryParams) ([]GetPostsBySubCategoryRow, error)
	GetPostsByUserId(ctx context.Context, uid string) ([]GetPostsByUserIdRow, error)
	GetUser(ctx context.Context, uid string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
