// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sub_category.sql

package db

import (
	"context"
)

const createSubCategory = `-- name: CreateSubCategory :one
INSERT INTO "sub_category" (
  "category_name"
) VALUES (
  $1
) RETURNING category_name, created_at
`

func (q *Queries) CreateSubCategory(ctx context.Context, categoryName string) (SubCategory, error) {
	row := q.db.QueryRow(ctx, createSubCategory, categoryName)
	var i SubCategory
	err := row.Scan(&i.CategoryName, &i.CreatedAt)
	return i, err
}

const getSubCategory = `-- name: GetSubCategory :one
SELECT category_name, created_at FROM "sub_category"
WHERE "category_name" = $1
`

func (q *Queries) GetSubCategory(ctx context.Context, categoryName string) (SubCategory, error) {
	row := q.db.QueryRow(ctx, getSubCategory, categoryName)
	var i SubCategory
	err := row.Scan(&i.CategoryName, &i.CreatedAt)
	return i, err
}
