// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (
  "uid",
  "username",
  "country_code"
) VALUES (
  $1, $2, $3
) RETURNING user_id, uid, username, self_intro, profile_image_url, banner_image_url, country_code, created_at
`

type CreateUserParams struct {
	Uid         string  `json:"uid"`
	Username    string  `json:"username"`
	CountryCode *string `json:"country_code"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Uid, arg.Username, arg.CountryCode)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Uid,
		&i.Username,
		&i.SelfIntro,
		&i.ProfileImageUrl,
		&i.BannerImageUrl,
		&i.CountryCode,
		&i.CreatedAt,
	)
	return i, err
}

const getFollowUsers = `-- name: GetFollowUsers :many
SELECT
"user"."user_id", 
"user"."username"
FROM "user"
JOIN "follow_user"
ON "user"."user_id" = "follow_user"."follow_user_id"
WHERE "follow_user"."user_id" = $1
`

type GetFollowUsersRow struct {
	UserID   int64  `json:"user_id"`
	Username string `json:"username"`
}

func (q *Queries) GetFollowUsers(ctx context.Context, userID int64) ([]GetFollowUsersRow, error) {
	rows, err := q.db.Query(ctx, getFollowUsers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowUsersRow{}
	for rows.Next() {
		var i GetFollowUsersRow
		if err := rows.Scan(&i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT user_id, uid, username, self_intro, profile_image_url, banner_image_url, country_code, created_at FROM "user"
WHERE "uid" = $1
`

func (q *Queries) GetUser(ctx context.Context, uid string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, uid)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Uid,
		&i.Username,
		&i.SelfIntro,
		&i.ProfileImageUrl,
		&i.BannerImageUrl,
		&i.CountryCode,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, uid, username, self_intro, profile_image_url, banner_image_url, country_code, created_at FROM "user"
WHERE "username" = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Uid,
		&i.Username,
		&i.SelfIntro,
		&i.ProfileImageUrl,
		&i.BannerImageUrl,
		&i.CountryCode,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE "user" SET
  "username" = COALESCE($1, "username"),
  "profile_image_url" = COALESCE($2, "profile_image_url"),
  "banner_image_url" = COALESCE($3, "banner_image_url")
WHERE "uid" = $4
RETURNING user_id, uid, username, self_intro, profile_image_url, banner_image_url, country_code, created_at
`

type UpdateUserParams struct {
	Username        *string `json:"username"`
	ProfileImageUrl *string `json:"profile_image_url"`
	BannerImageUrl  *string `json:"banner_image_url"`
	Uid             string  `json:"uid"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.ProfileImageUrl,
		arg.BannerImageUrl,
		arg.Uid,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Uid,
		&i.Username,
		&i.SelfIntro,
		&i.ProfileImageUrl,
		&i.BannerImageUrl,
		&i.CountryCode,
		&i.CreatedAt,
	)
	return i, err
}
