// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: user.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT user_id, uid, username, currency, created_at FROM "user"
WHERE "uid" = $1
`

func (q *Queries) GetUser(ctx context.Context, uid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, uid)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Uid,
		&i.Username,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
