Project Nijimas {
  database_type: 'PostgreSQL'
  Note: '''
    # Nijimas Database
    **markdown content here**
  '''
}

Table user as U {
  user_id bigserial [pk]
  uid varchar(255) [not null]
  username varchar(255) [not null]
  country_code char(2)
  created_at timestamptz [not null, default: `now()`]

  indexes {
    uid
    username
  }
}

Table post as P {
  post_id bigserial [pk]
  user_id bigint [ref: > U.user_id, not null]
  main_category varchar(255) [ref: > MC.category_name, not null]
  post_text text 
  photo_url varchar(2000)
  location geometry
  meal_flag boolean [not null, default: false]
  public_type_no char(1) [not null, note: '1:公開、2:フォロワーにのみ公開、3:非公開']
  created_at timestamptz [not null, default: `now()`]

  indexes {
    user_id
    created_at
  }
}

Table post_subcategory as PS {
  post_subcategory_id bigserial [pk]
  post_id bigint [ref: > P.post_id, not null]
  subcategory_no char(1) [not null]
  sub_category varchar(255) [ref: > SC.category_name, not null]

  indexes {
    (post_id, sub_category)
  }
}

Table favorite as FA {
  favorite_id bigserial [pk]
  post_id bigint [ref: > P.post_id, not null]
  user_id bigint [ref: > U.user_id, not null]
  created_at timestamptz [not null, default: `now()`]
}

Table main_category as MC {
  category_name varchar(255) [pk]
  created_at timestamptz [not null, default: `now()`]
}

Table sub_category as SC {
  category_name varchar(255) [pk]
  created_at timestamptz [not null, default: `now()`]
}

Table follow_user as FU {
  follow_id bigserial [pk]
  user_id bigint [ref: > U.user_id, not null]
  follow_user_id bigint [ref: > U.user_id, not null]
  created_at timestamptz [not null, default: `now()`]
}

Table meal as M {
  meal_id bigserial [pk]
  post_id bigint [ref: > P.post_id, not null]
  user_id bigint [ref: > U.user_id, not null]
  calorie bigint [not null, default: 0]
  created_at timestamptz [not null, default: `now()`]
}
